### ISSUE TITLE
Staking management and information

### ISSUE THREAD

**Issue by aaroncox** [greymass/2nicove#62]
### Description
Milestone dedicated to staking management of the system token in 2nicove.

### Issues
- [x] https://github.com/greymass/2nicove/issues/53
- [x] https://github.com/greymass/2nicove/issues/52
- [x] https://github.com/greymass/2nicove/issues/133

**Comment by aaroncox** [comment]
Replace with: https://github.com/greymass/2nicove/issues/53
