### ISSUE TITLE
RAM Market

### ISSUE THREAD

**Issue by sandroguras** [greymass/2nicove#66]
### Description
Milestone dedicated to RAM management in 2nicove.

### Issues
- [x] https://github.com/greymass/2nicove/issues/43
- [x] https://github.com/greymass/2nicove/issues/44
- [x] https://github.com/greymass/2nicove/issues/45
- [x] https://github.com/greymass/2nicove/issues/46
- [x] https://github.com/greymass/2nicove/issues/72
