### ISSUE TITLE
MetaMask Snap

### ISSUE THREAD

**Issue by sandroguras** [greymass/2nicove#73]
### Description
Milestone dedicated to MetaMask snap integration in 2nicove.

### Issues
- [x] https://github.com/greymass/2nicove/issues/75
- [x] https://github.com/greymass/2nicove/issues/76
- [x] https://github.com/greymass/2nicove/issues/77
- [x] https://github.com/greymass/2nicove/issues/74
- [x] #169
